### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abobickabubachiroww** [pyroch/TwitchGrobs#10]
![image](https://user-images.githubusercontent.com/87073954/124961344-ff812e80-e025-11eb-9c3c-72c7a488a6e6.png)

**Comment by pyroch** [comment]
Does it stop right after you open it or after some amount of time?
Make sure you got  .NET Framework 4.7 installed.

**Comment by pyroch** [comment]
also make sure you got latest version of Google Chrome installed.
