### ISSUE TITLE
The program does not work correctly.

### ISSUE THREAD

**Issue by WildCharley** [pyroch/TwitchGrobs#11]
The program does not work correctly.
Here's a video of what's wrong with it?
https://youtu.be/yGdppIwDCkM

**Comment by Toxenskiy** [comment]
This developer may have been hacked. the last update is a fake update, which brought nothing new, it was made to improve among other programs. Also in the tags in the executable file there is a virus.

**Comment by pyroch** [comment]
> This developer may have been hacked. the last update is a fake update, which brought nothing new, it was made to improve among other programs. Also in the tags in the executable file there is a virus.

No I'm not hacked, the last update wasn't fake if you talking about 1.0.7, It brought nothing new except updated chromedriver which always updates within Google Chrome update, so if the chromedriver is older than latest google chrome the program wont work. I also updated xpaths.
There is no virus in program and I'm not sure why some people think there is a virus. I mean don't use it then or use it on your own risk it's okay.
