### ISSUE TITLE
Streamers skip

### ISSUE THREAD

**Issue by battlekicker** [pyroch/TwitchGrobs#16]
Why it writes "Nothing to watch" or "No drops here now" when it actually watching something whos live and contains in streamers.txt? After that it's turning off the stream.
![chrome_roltn2gjv1](https://user-images.githubusercontent.com/63844239/148636399-a615d67b-8e9d-47a4-873d-0b81c37556fe.jpg)
![chrome_DTXauA8uVk](https://user-images.githubusercontent.com/63844239/148636405-3ef81015-2deb-4ec6-bf5b-f1c3a0576955.png)

**Comment by pyroch** [comment]
Hello. Yeah should be fixed from now on https://github.com/pyroch/TwitchGrobs/releases/tag/1.1.0 
Didn't update the bot for a while and twitch changed some stuff a little bit.
