### ISSUE TITLE
Claiming nonfunctional

### ISSUE THREAD

**Issue by skupfer** [pyroch/TwitchGrobs#2]
As per titel. The bot doesn't claim drops. No errors, stuck on 100% in console (checked hours later, was a 30min watch only)

**Comment by pyroch** [comment]
Did it say "100% on one of drops. Claiming and switching streamer"? Or was it just showing "Percentage of the drop Percentage of drop: 100"?

**Comment by skupfer** [comment]
The latter, "Percentage of drop: 100". Won't do anything else in this state.

**Comment by Stiphr** [comment]
works fine for me
