### ISSUE TITLE
No EXE file in latest

### ISSUE THREAD

**Issue by carterlasalle** [pyroch/TwitchGrobs#8]
Whenever I download, there is no EXE for me to open besides chromedriver

**Comment by pyroch** [comment]
exe file most likely gets removed by windows defender or some other kind of anti-virus if that's happens after you extract it. Other than that, I just checked zip file again, there is clearly 3 files in it
![image](https://user-images.githubusercontent.com/5215882/123593016-abd93e80-d7f6-11eb-928a-d60bb804685a.png)

**Comment by mariogarridopt** [comment]
@pyroch you are right, the files are removed by the windows defender. Windows thinks this is virus
