### ISSUE TITLE
No drops here now. But drops here now

### ISSUE THREAD

**Issue by magicpigomg** [pyroch/TwitchGrobs#9]
![Screenshot_3](https://user-images.githubusercontent.com/87029756/124630095-c06aa600-de8a-11eb-9286-6d4468aa5bb2.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/87029756/124630105-c2346980-de8a-11eb-8e3d-4ab0459d5353.jpg)

**Comment by RoddieMi** [comment]
I second this issue. It would cycle before the drop was earned.

**Comment by Toxenskiy** [comment]
im fixed this

**Comment by RoddieMi** [comment]
Having the same issue again today during Rust drop streams. Just wanted to let you know.

**Comment by pyroch** [comment]
Whenever there is a progress on a drop in profile
![image](https://user-images.githubusercontent.com/5215882/142779653-f2cc9430-48e5-4692-ab12-d33623112de6.png)
it shows the percent, if there is no it shows no drops here, also because of twitch sometimes need to watch stream for like 10 minutes to get this message, and then program works fine.

**Comment by FadingToJosh** [comment]
> Whenever there is a progress on a drop in profile ![image](https://user-images.githubusercontent.com/5215882/142779653-f2cc9430-48e5-4692-ab12-d33623112de6.png) it shows the percent, if there is no it shows no drops here, also because of twitch sometimes need to watch stream for like 10 minutes to get this message, and then program works fine.

Any idea why I'm still getting this? 
![image](https://user-images.githubusercontent.com/1158510/153070633-2b82d77d-5721-416a-be1e-8d71199059a2.png)
![image](https://user-images.githubusercontent.com/1158510/153070672-5240e672-6b78-4059-b05f-642980321164.png)
![image](https://user-images.githubusercontent.com/1158510/153070705-dee1398b-485b-448d-b35f-a9db43275b76.png)
